<a href="https://colab.research.google.com/github/SonalikaSingh/AML/blob/linear_regression_one_i%2Fo/Multivariable_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
data=pd.read_excel('CB_multi_lr.xlsx')
data.head(3)

Unnamed: 0  Unnamed: 1  Unnamed: 2  salary  exper  test_score  interview
0         NaN         NaN         NaN   50000    NaN         8.0          9
1         NaN         NaN         NaN   45000    NaN         8.0          6
2         NaN         NaN         NaN   60000    5.0         6.0          7

In [6]:
c=['salary','exper','test_score','interview']
df=data[c]
df.head(5)

salary  exper  test_score  interview
0   50000    NaN         8.0          9
1   45000    NaN         8.0          6
2   60000    5.0         6.0          7
3   65000    2.0        10.0         10
4   70000    7.0         9.0          6

Data Preprocessing: Fill NA values with median value of a column

In [19]:
df.exper.mean()

6.25

In [20]:
df.exper = df.exper.fillna(df.exper.mean())
df

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:5170: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


salary  exper  test_score  interview
0   50000    6.0         8.0          9
1   45000    6.0         8.0          6
2   60000    5.0         6.0          7
3   65000    2.0        10.0         10
4   70000    7.0         9.0          6
5   62000    3.0         7.0         10
6   72000   10.0         8.0          7
7   80000   11.0         7.0          8

In [9]:
df.test_score.median()

8.0

In [21]:
df.test_score=df.test_score.fillna(df.test_score.mean())

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:5170: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [22]:
df.head(5)

salary  exper  test_score  interview
0   50000    6.0         8.0          9
1   45000    6.0         8.0          6
2   60000    5.0         6.0          7
3   65000    2.0        10.0         10
4   70000    7.0         9.0          6

Creating linear regression model

In [23]:

model = linear_model.LinearRegression()
model.fit(df.drop('salary',axis='columns'),df.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [24]:
model.coef_

array([2813.00813008, 1333.33333333, 2926.82926829])

In [25]:
model.intercept_

11869.91869918695

2 yr experience, 9 test score, 6 interview score

12 yr experience, 10 test score, 10 interview score

In [26]:
model.predict([[2, 9, 6]])

array([47056.91056911])

In [27]:
model.predict([[12, 10, 10]])

array([88227.64227642])